#!/bin/bash

echo "🔧 Google OAuth 설정 가이드"
echo "=========================="
echo ""
echo "✅ 서버 설정 완료!"
echo "   NEXTAUTH_URL이 https://xn--oj4b21j.com 으로 설정되었습니다."
echo ""
echo "📋 Google Cloud Console에서 설정해야 할 사항:"
echo ""
echo "1. Google Cloud Console 접속:"
echo "   https://console.cloud.google.com/apis/credentials"
echo ""
echo "2. OAuth 2.0 클라이언트 ID 선택:"
echo "   Client ID: 420729489239-prg64c6co4rqa99sdmacpm1fg03upcu5.apps.googleusercontent.com"
echo ""
echo "3. 승인된 리디렉션 URI에 다음 URL들을 추가:"
echo "   ✅ https://xn--oj4b21j.com/api/auth/callback/google"
echo "   ✅ https://성장.com/api/auth/callback/google"
echo "   ✅ http://localhost:3000/api/auth/callback/google (개발용)"
echo ""
echo "4. 승인된 JavaScript 원본에 다음 URL들을 추가:"
echo "   ✅ https://xn--oj4b21j.com"
echo "   ✅ https://성장.com"
echo "   ✅ http://localhost:3000 (개발용)"
echo ""
echo "5. 저장 버튼 클릭"
echo ""
echo "⚠️  중요: 'your-url-here'가 있다면 반드시 삭제하세요!"
echo ""
echo "📝 현재 설정된 값:"
echo "   NEXTAUTH_URL: https://xn--oj4b21j.com"
echo "   GOOGLE_CLIENT_ID: 420729489239-prg64c6co4rqa99sdmacpm1fg03upcu5.apps.googleusercontent.com"
echo ""
echo "🔄 설정 완료 후 브라우저 캐시를 삭제하고 다시 시도하세요."