#!/bin/bash

echo "🎯 김시온 학생 10레벨 카드 서버 직접 생성 명령어"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "📋 프로덕션 서버(43.200.27.173)에서 실행할 명령어:"
echo ""
echo "cd /home/ubuntu/vacation"
echo ""
echo "# 방법 1: Node.js 스크립트로 직접 생성"
echo "DATABASE_URL=\"postgresql://postgres:postgres@localhost:5432/studylog_db\" node -e \""
echo "const { PrismaClient } = require('@prisma/client');"
echo "const prisma = new PrismaClient();"
echo ""
echo "(async () => {"
echo "  try {"
echo "    // 김시온 학생 찾기"
echo "    const user = await prisma.user.findUnique({"
echo "      where: { email: 'kimsion70823@gmail.com' },"
echo "      include: { studentProfile: { include: { levelImages: true } } }"
echo "    });"
echo ""
echo "    if (!user?.studentProfile) {"
echo "      console.log('❌ 김시온 학생을 찾을 수 없습니다.');"
echo "      return;"
echo "    }"
echo ""
echo "    console.log(\`✅ 김시온 학생 발견: \${user.name} (레벨 \${user.studentProfile.level})\`);"
echo ""
echo "    // 기존 10레벨 카드 삭제"
echo "    const existing = await prisma.levelImage.findFirst({"
echo "      where: { studentId: user.studentProfile.id, level: 10 }"
echo "    });"
echo ""
echo "    if (existing) {"
echo "      await prisma.levelImage.delete({ where: { id: existing.id } });"
echo "      console.log('🗑️ 기존 10레벨 카드 삭제 완료');"
echo "    }"
echo ""
echo "    // 새 10레벨 카드 생성"
echo "    const newCard = await prisma.levelImage.create({"
echo "      data: {"
echo "        studentId: user.studentProfile.id,"
echo "        level: 10,"
echo "        imageUrl: '/level-cards/kim-sion-level-10-1757486919979.svg',"
echo "        prompt: 'Apple Scholar Level 10 - Korean webtoon style character card',"
echo "        strength: user.studentProfile.strength,"
echo "        intelligence: user.studentProfile.intelligence,"
echo "        dexterity: user.studentProfile.dexterity,"
echo "        charisma: user.studentProfile.charisma,"
echo "        vitality: user.studentProfile.vitality,"
echo "        totalXP: user.studentProfile.totalXP,"
echo "        totalMinutes: user.studentProfile.totalMinutes"
echo "      }"
echo "    });"
echo ""
echo "    console.log('🎉 김시온 10레벨 카드 생성 완료!');"
echo "    console.log(\`📋 카드 ID: \${newCard.id}\`);"
echo "    console.log('💡 갤러리에서 확인 가능합니다!');"
echo ""
echo "  } catch (error) {"
echo "    console.error('💥 오류:', error);"
echo "  } finally {"
echo "    await prisma.\\\$disconnect();"
echo "  }"
echo "})();"
echo "\""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎯 또는 더 간단하게:"
echo ""
echo "# 방법 2: SQL 직접 실행"
echo "docker exec -it studylog_postgres psql -U postgres -d studylog_db -c \""
echo "INSERT INTO \\\"LevelImage\\\" ("
echo "  id, \\\"studentId\\\", level, \\\"imageUrl\\\", prompt,"
echo "  strength, intelligence, dexterity, charisma, vitality,"
echo "  \\\"totalXP\\\", \\\"totalMinutes\\\", \\\"createdAt\\\", \\\"updatedAt\\\""
echo ") SELECT "
echo "  'kim-sion-level-10-' || EXTRACT(EPOCH FROM NOW())::text,"
echo "  sp.id, 10, '/level-cards/kim-sion-level-10-1757486919979.svg',"
echo "  'Apple Scholar Level 10 Card',"
echo "  sp.strength, sp.intelligence, sp.dexterity, sp.charisma, sp.vitality,"
echo "  sp.\\\"totalXP\\\", sp.\\\"totalMinutes\\\", NOW(), NOW()"
echo "FROM \\\"StudentProfile\\\" sp"
echo "JOIN \\\"User\\\" u ON sp.\\\"userId\\\" = u.id"
echo "WHERE u.email = 'kimsion70823@gmail.com'"
echo "ON CONFLICT DO NOTHING;"
echo "\""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ 실행 후 확인:"
echo "- 김시온 학생이 갤러리(/dashboard/gallery)에서 10레벨 카드 확인"
echo "- 프로필 페이지에서도 카드 표시됨"
echo ""
echo "🎨 생성되는 카드:"
echo "- Apple Scholar 캐릭터"
echo "- 김시온 학생의 실제 능력치 반영"
echo "- 한국 웹툰 스타일, 브론즈 테마"